cellIdPreamble: "cell-"
gradientMode: "hue"

cells:
  edge_BE_DE_AB:
    dataRef: edge_BE_DE_AB
    flowAnimation: {thresholdOffValue: 0, thresholdLwrValue: 1, thresholdLwrDurationSecs: 1, thresholdUprValue: 1000, thresholdUprDurationSecs: 0.15}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [edge]
  edge_BE_DE_BA:
    dataRef: edge_BE_DE_BA
    flowAnimation: {thresholdOffValue: 0, thresholdLwrValue: 1, thresholdLwrDurationSecs: 1, thresholdUprValue: 1000, thresholdUprDurationSecs: 0.15}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [edge]
  edge_BE_FR_AB:
    dataRef: edge_BE_FR_AB
    flowAnimation: {thresholdOffValue: 0, thresholdLwrValue: 1, thresholdLwrDurationSecs: 1, thresholdUprValue: 1000, thresholdUprDurationSecs: 0.15}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [edge]
  edge_BE_FR_BA:
    dataRef: edge_BE_FR_BA
    flowAnimation: {thresholdOffValue: 0, thresholdLwrValue: 1, thresholdLwrDurationSecs: 1, thresholdUprValue: 1000, thresholdUprDurationSecs: 0.15}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [edge]
  edge_DK_DE_AB:
    dataRef: edge_DK_DE_AB
    flowAnimation: {thresholdOffValue: 0, thresholdLwrValue: 1, thresholdLwrDurationSecs: 1, thresholdUprValue: 1000, thresholdUprDurationSecs: 0.15}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [edge]
  edge_DK_DE_BA:
    dataRef: edge_DK_DE_BA
    flowAnimation: {thresholdOffValue: 0, thresholdLwrValue: 1, thresholdLwrDurationSecs: 1, thresholdUprValue: 1000, thresholdUprDurationSecs: 0.15}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [edge]
  edge_FR_DE_AB:
    dataRef: edge_FR_DE_AB
    flowAnimation: {thresholdOffValue: 0, thresholdLwrValue: 1, thresholdLwrDurationSecs: 1, thresholdUprValue: 1000, thresholdUprDurationSecs: 0.15}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [edge]
  edge_FR_DE_BA:
    dataRef: edge_FR_DE_BA
    flowAnimation: {thresholdOffValue: 0, thresholdLwrValue: 1, thresholdLwrDurationSecs: 1, thresholdUprValue: 1000, thresholdUprDurationSecs: 0.15}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [edge]
  edge_NL_BE_AB:
    dataRef: edge_NL_BE_AB
    flowAnimation: {thresholdOffValue: 0, thresholdLwrValue: 1, thresholdLwrDurationSecs: 1, thresholdUprValue: 1000, thresholdUprDurationSecs: 0.15}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [edge]
  edge_NL_BE_BA:
    dataRef: edge_NL_BE_BA
    flowAnimation: {thresholdOffValue: 0, thresholdLwrValue: 1, thresholdLwrDurationSecs: 1, thresholdUprValue: 1000, thresholdUprDurationSecs: 0.15}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [edge]
  edge_NL_DE_AB:
    dataRef: edge_NL_DE_AB
    flowAnimation: {thresholdOffValue: 0, thresholdLwrValue: 1, thresholdLwrDurationSecs: 1, thresholdUprValue: 1000, thresholdUprDurationSecs: 0.15}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [edge]
  edge_NL_DE_BA:
    dataRef: edge_NL_DE_BA
    flowAnimation: {thresholdOffValue: 0, thresholdLwrValue: 1, thresholdLwrDurationSecs: 1, thresholdUprValue: 1000, thresholdUprDurationSecs: 0.15}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [edge]
  edge_NL_DK_AB:
    dataRef: edge_NL_DK_AB
    flowAnimation: {thresholdOffValue: 0, thresholdLwrValue: 1, thresholdLwrDurationSecs: 1, thresholdUprValue: 1000, thresholdUprDurationSecs: 0.15}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [edge]
  edge_NL_DK_BA:
    dataRef: edge_NL_DK_BA
    flowAnimation: {thresholdOffValue: 0, thresholdLwrValue: 1, thresholdLwrDurationSecs: 1, thresholdUprValue: 1000, thresholdUprDurationSecs: 0.15}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [edge]
  lab_BE_DE_AB:
    dataRef: edge_BE_DE_AB
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [label]
  lab_BE_DE_BA:
    dataRef: edge_BE_DE_BA
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [label]
  lab_BE_FR_AB:
    dataRef: edge_BE_FR_AB
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [label]
  lab_BE_FR_BA:
    dataRef: edge_BE_FR_BA
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [label]
  lab_DK_DE_AB:
    dataRef: edge_DK_DE_AB
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [label]
  lab_DK_DE_BA:
    dataRef: edge_DK_DE_BA
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [label]
  lab_FR_DE_AB:
    dataRef: edge_FR_DE_AB
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [label]
  lab_FR_DE_BA:
    dataRef: edge_FR_DE_BA
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [label]
  lab_NL_BE_AB:
    dataRef: edge_NL_BE_AB
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [label]
  lab_NL_BE_BA:
    dataRef: edge_NL_BE_BA
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [label]
  lab_NL_DE_AB:
    dataRef: edge_NL_DE_AB
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [label]
  lab_NL_DE_BA:
    dataRef: edge_NL_DE_BA
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [label]
  lab_NL_DK_AB:
    dataRef: edge_NL_DK_AB
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [label]
  lab_NL_DK_BA:
    dataRef: edge_NL_DK_BA
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [label]
  txt_BE_code:
    dataRef: txt_BE_code
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]
  txt_BE_export:
    dataRef: txt_BE_export
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]
  txt_BE_import:
    dataRef: txt_BE_import
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]
  txt_DE_code:
    dataRef: txt_DE_code
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]
  txt_DE_export:
    dataRef: txt_DE_export
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]
  txt_DE_import:
    dataRef: txt_DE_import
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]
  txt_DK_code:
    dataRef: txt_DK_code
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]
  txt_DK_export:
    dataRef: txt_DK_export
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]
  txt_DK_import:
    dataRef: txt_DK_import
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]
  txt_FR_code:
    dataRef: txt_FR_code
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]
  txt_FR_export:
    dataRef: txt_FR_export
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]
  txt_FR_import:
    dataRef: txt_FR_import
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]
  txt_NL_code:
    dataRef: txt_NL_code
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]
  txt_NL_export:
    dataRef: txt_NL_export
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]
  txt_NL_import:
    dataRef: txt_NL_import
    label: {separator: space, units: MW, labelColor: ""}
    thresholds: [{color: green, level: 0}, {color: orange, level: 500}, {color: red, level: 1000}]
    tags: [node-total]

  quarter_label:
    dataRef: quarter_label
    label:
      separator: ""
      labelFontWeight: bold
      units: ""
    labelColor: "#E2E8F0"
    labelFontSize: 22
